"""empty message

Revision ID: 03fc9a0b44fd
Revises: 7f775089b078
Create Date: 2021-08-24 18:15:09.371028+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03fc9a0b44fd'
down_revision = '7f775089b078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
