"""empty message

Revision ID: 7f775089b078
Revises: a7d2887aa71f
Create Date: 2021-08-24 17:35:56.864766+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f775089b078'
down_revision = 'a7d2887aa71f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('active', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'active')
    # ### end Alembic commands ###
