name: Static Analysis

on: [push]

jobs:
  pylint:
    # Use ubuntu-20.04 LTS.
    runs-on: ubuntu-20.04
    steps:
      # Setup python3.9, x64.
      - uses: actions/checkout@v2
      - name: Set up python3.9, x64
        uses: actions/setup-python@v2
        with:
            python-version: '3.9'
            architecture: 'x64'
        # Info.
        run: python -c "import sys; print(sys.version)"
      - name: Install requirements
        run: |
          python -m pip install --no-cache-dir --upgrade pip setuptools wheel
          python -m pip install --no-cache-dir -r requirements.txt
      - name: Run pylint
        run: python -m pylint --exit-zero innonymous
